import type {Metadata} from "next";
import "./globals.css";
import ToasterComponent from "@/components/ToastComponent";
// ----------------------------------------------------------------------->


export const metadata: Metadata = {
    title: "AI Chatbot",
    description: "Generated by Reza Hosseinzadeh",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
        <body
            className={`h-screen w-full flex flex-col`}
        >
        <ToasterComponent/>
        {children}
        </body>
        </html>
    );
}